In [1]:
from scipy.special import expit
import os
import gzip
import cPickle
import wget
import random
import numpy as np
from scipy.special import softmax

In [2]:
def vectorized_result(y):
    e = np.zeros((10, 1))
    e[y] = 1.0
    return e

def load_mnist():
    if not os.path.exists(os.path.join(os.curdir, 'data')):
        os.mkdir(os.path.join(os.curdir, 'data'))
        wget.download('http://deeplearning.net/data/mnist/mnist.pkl.gz', out='data')

    data_file = gzip.open(os.path.join(os.curdir, 'data', 'mnist.pkl.gz'), 'rb')
    training_data, validation_data, test_data = cPickle.load(data_file)
    data_file.close()

    training_inputs = [np.reshape(x, (784, 1)) for x in training_data[0]]
    training_results = [vectorized_result(y) for y in training_data[1]]
    training_data = zip(training_inputs, training_results)

    validation_inputs = [np.reshape(x, (784, 1)) for x in validation_data[0]]
    validation_results = validation_data[1]
    validation_data = zip(validation_inputs, validation_results)

    test_inputs = [np.reshape(x, (784, 1)) for x in test_data[0]]
    test_data = zip(test_inputs, test_data[1])
    return training_data, validation_data, test_data
train_data, valid_data, test_data = load_mnist()

In [3]:
def softmax(z):
        return softmax(z, axis=1)

def ReLU(z):
    return np.maximum(z, 0)
    
class NN(object):
    def __init__(self, network_units, activation_fn):
        self.network_units = network_units
        if activation_fn =="softmax":
            self.activation_fn=softmax
        elif activation_fn =="ReLU":
            self.activation_fn = ReLU
        self.parameters = {}
        self.initialize_weights()
        
    
    def initialize_weights(self):
        
        for i in xrange(len(self.network_units)-1):
            self.parameters["b"+str(i)] = np.zeros((self.network_units[i+1]))
            self.parameters["w"+str(i)] = np.random.uniform( 
                            -np.sqrt(6/(self.network_units[i]+self.network_units[i+1])), 
                            np.sqrt(6/(self.network_units[i]+self.network_units[i+1])),
                            size=(self.network_units[i],self.network_units[i+1])
                                                          )
            
    
    def forward(self, x):
        h1 = np.dot(x, self.parameters["w0"]) + self.parameters["b0"]
        h2 = np.dot(h1, self.parameters["w1"]) + self.parameters["b1"]
        out = softmax(np.dot(h2, self.parameters["w2"]) + self.parameters["b2"])
        return out
        

In [4]:
myNet = NN([784,400,400,10], "ReLU")

In [5]:
myNet.forward(train_data)

ValueError: setting an array element with a sequence.

In [6]:
x = np.random.randn(5,3)
print(x)
print("relu")
print(np.maximum(x,0))

[[ 0.91278889 -0.44784541 -0.71139208]
 [-0.06102688  0.57347456  0.19236608]
 [-0.56975286 -0.82880996 -1.23168905]
 [-0.02554462  0.72283349 -0.21321924]
 [-0.76397866 -0.666457    0.10755108]]
relu
[[0.91278889 0.         0.        ]
 [0.         0.57347456 0.19236608]
 [0.         0.         0.        ]
 [0.         0.72283349 0.        ]
 [0.         0.         0.10755108]]
